<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'title' => 'شقة للبيع في الرياض',
                'slug' => 'شقة-للبيع-الرياض',
                'description' => 'شقة فاخرة للبيع في حي الصحافة بمساحة 180 متر، 3 غرف نوم، 2 حمام، مطبخ راقي',
                'view' => 45,
                'is_urgent' => false,
                'discount' => 0,
                'address' => 'حي الصحافة، الرياض، السعودية',
                'type' => \App\Enums\ProductTypes::ESTATE->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'سيارة تويوتا كامري 2020',
                'slug' => 'تويوتا-كامري-2020',
                'description' => 'سيارة تويوتا كامري موديل 2020 اللون أبيض، فل كامل، ماشية 45000 كم فقط',
                'view' => 120,
                'is_urgent' => true,
                'discount' => 10,
                'address' => 'الرياض، السعودية',
                'type' => \App\Enums\ProductTypes::CAR->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'مدرسة النخبة الدولية',
                'slug' => 'مدرسة-النخبة-الدولية',
                'description' => 'مدرسة خاصة تقدم تعليماً متميزاً وفق المناهج الدولية',
                'view' => 30,
                'address' => 'حي النخيل، جدة، السعودية',
                'type' => \App\Enums\ProductTypes::SCHOOL->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'آيفون 13 برو ماكس',
                'slug' => 'آيفون-13-برو-ماكس',
                'description' => 'جوال آيفون 13 برو ماكس سعة 256 جيجا، اللون أزرق، بحالة ممتازة',
                'view' => 85,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::ELECTRONIC->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'مزرعة للبيع في القصيم',
                'slug' => 'مزرعة-للبيع-القصيم',
                'description' => 'مزرعة مساحتها 5000 متر مربع، تحتوي على بئر وبيت مزارع وأشجار نخيل',
                'view' => 25,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::FARM->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'فيلا فاخرة في جدة',
                'slug' => 'فيلا-فاخرة-جدة',
                'description' => 'فيلا فاخرة في حي الصفا، 5 غرف نوم، 3 حمامات، حديقة، مسبح',
                'view' => 60,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::ESTATE->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'سيارة هونداي أكسنت 2019',
                'slug' => 'هونداي-أكسنت-2019',
                'description' => 'سيارة هونداي أكسنت موديل 2019، اللون أسود، ماشية 60000 كم',
                'view' => 75,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::CAR->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'سامسونج جالاكسي S22',
                'slug' => 'سامسونج-جالاكسي-S22',
                'description' => 'جوال سامسونج جالاكسي S22 سعة 128 جيجا، اللون أخضر، بحالة الجديدة',
                'view' => 90,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::ELECTRONIC->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'مدرسة العودة ',
                'slug' => 'مدرسة-العودة',
                'description' => 'مدرسة خاصة تقدم تعليماً متميزاً وفق المناهج الدولية',
                'view' => 30,
                'type' => \App\Enums\ProductTypes::SCHOOL->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'شقة فاخرة ',
                'slug' => 'شقة-فاخرة',
                'description' =>"شقة فاخرة جداً",
                'view' => 30,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::ESTATE->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'سيارة سوناتا أكسنت 2019',
                'slug' => 'سوناتا-أكسنت-2019',
                'description' => 'سيارة هونداي أكسنت موديل 2019، اللون أسود، ماشية 60000 كم',
                'view' => 75,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::CAR->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'سيارة كيا سيراتو 2019',
                'slug' => 'كيا-سيراتو-2019',
                'description' => 'سيارة هونداي أكسنت موديل 2019، اللون أسود، ماشية 60000 كم',
                'view' => 75,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::CAR->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'جالاكسي S22',
                'slug' => 'جالاكسي-S22',
                'description' => 'جوال سامسونج جالاكسي S22 سعة 128 جيجا، اللون أخضر، بحالة الجديدة',
                'view' => 90,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::ELECTRONIC->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ماك بوك برو',
                'slug' => 'ماك-بوك-برو',
                'description' => 'لابتوب ماك بوك برو من آبل، شاشة 16 بوصة، معالج M1 Pro، سعة 512 جيجا',
                'view' => 70,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::ELECTRONIC->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'آيباد برو',
                'slug' => 'آيباد-برو',
                'description' => 'تابلت آيباد برو من آبل، شاشة 12.9 بوصة، سعة 256 جيجا، بحالة ممتازة',
                'view' => 65,
                'is_urgent' => true,
                'discount' => 10,
                'type' => \App\Enums\ProductTypes::ELECTRONIC->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'مزرعة للإيجار في الخرج',
                'slug' => 'مزرعة-للإيجار-الخرج',
                'description' => 'مزرعة مساحتها 3000 متر مربع، تحتوي على بئر وبيت مزارع وأشجار نخيل',
                'view' => 20,
                'type' => \App\Enums\ProductTypes::FARM->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'مزرعة للبيع في الطائف',
                'slug' => 'مزرعة-للبيع-الطائف',
                'description' => 'مزرعة مساحتها 8000 متر مربع، تحتوي على بئر وبيت مزارع وأشجار نخيل',
                'view' => 35,
                'type' => \App\Enums\ProductTypes::FARM->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'فيلا فاخرة في الرياض',
                'slug' => 'فيلا-فاخرة-الرياض',
                'description' => 'فيلا فاخرة في حي الياسمين، 6 غرف نوم، 4 حمامات، حديقة، مسبح',
                'view' => 50,
                'type' => \App\Enums\ProductTypes::ESTATE->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'سيارة نيسان باترول 2021',
                'slug' => 'نيسان-باترول-2021',
                'description' => 'سيارة نيسان باترول موديل 2021، اللون أسود، فل كامل، ماشية 30000 كم',
                'view' => 100,
                'type' => \App\Enums\ProductTypes::CAR->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'شقة للبيع في جدة',
                'slug' => 'شقة-للبيع-جدة',
                'description' => 'شقة فاخرة في حي النخيل، 3 غرف نوم، 2 حمام، مطبخ راقي',
                'view' => 40,
                'type' => \App\Enums\ProductTypes::ESTATE->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'مزرعة للبيع في أبها',
                'slug' => 'مزرعة-للبيع-أبها',
                'description' => 'مزرعة مساحتها 7000 متر مربع، تحتوي على بئر وبيت مزارع وأشجار نخيل',
                'view' => 30,
                'type' => \App\Enums\ProductTypes::FARM->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'سيارة مرسيدس GLC 2020',
                'slug' => 'مرسيدس-GLC-2020',
                'description' => 'سيارة مرسيدس GLC موديل 2020، اللون أبيض، فل كامل، ماشية 25000 كم',
                'view' => 80,
                'type' => \App\Enums\ProductTypes::CAR->value,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::query()->create($productData);

            // Add a fake image from an online source
            $product->addMediaFromUrl('https://picsum.photos/200/300')
                     ->toMediaCollection('images');
        }
    }
}
